# Generated by Django 3.2.8 on 2021-10-12 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'skills',
                'managed': False,
            },
        ),
    ]
